# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  parse-build-test:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          site:
            - 'site/**'
          database:
            - 'database/**'

    - name: Validate YAML
      id: json-yaml-validate
      uses: GrantBirki/json-yaml-validate@v2.4.0 # replace with the latest version
      with:
        comment: "true" # enable comment mode

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: site/package-lock.json

    - name: Build database
      # if: steps.filter.outputs.database == 'true'
      run: |
        npm ci
        npm run cli -- --dir ./database/persons --file ./export/tree.json --local

    - name: Copy file
      # if: steps.filter.outputs.database == 'true'
      run: cp export/tree.json export/styles.json site/src/js/

    - name: Build site
      if: steps.filter.outputs.site == 'true'
      working-directory: site
      run: |
        npm ci
        npm run build --if-present

  parse:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Validate YAML
      id: json-yaml-validate
      uses: GrantBirki/json-yaml-validate@v2.4.0 # replace with the latest version
      with:
        comment: "true" # enable comment mode

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          site:
            - 'site/**'
          database:
            - 'database/**'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: site/package-lock.json

    - name: Build
      run: |
        npm ci
        npm run cli -- --dir ./database/persons --file ./export/tree.json

    - name: Copy
      run: cp export/tree.json export/styles.json site/src/js/

    - name: Commit
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git checkout -b gh-pages
        git add export/tree.json export/styles.json site/src/js/tree.json site/src/js/styles.json
        git commit -m "Automated file creation."
        git push -f origin gh-pages

  build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: parse
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          site:
            - 'site/**'
          database:
            - 'database/**'
    - name: Checkout
      uses: actions/checkout@v3
      with:
       ref: gh-pages

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: site/package-lock.json
    - name: Image cache
      if: steps.filter.outputs.database == 'true'
      run: |
        npm ci
        mkdir -p site/dist/images/cache || true
        npm run image-cache -- --dir=site/dist/images/cache --dirPrefix=images/cache --sourceFile=export/tree.json --targetFile=site/src/js/tree.json

    - name: Build
      if: steps.filter.outputs.database == 'true' || steps.filter.outputs.site == 'true'
      working-directory: site
      run: |
        npm ci
        npm run build --if-present

    - name: Copy static assets
      if: steps.filter.outputs.database == 'true' || steps.filter.outputs.site == 'true'
      working-directory: site
      run: cp src/images/budotree_h.mp4 dist/images/budotree_h.mp4 && cp src/preview.html dist/preview.html && cp src/images/budotree_timeline.mp4 dist/images/budotree_timeline.mp4

    - name: Commit
      if: steps.filter.outputs.database == 'true' || steps.filter.outputs.site == 'true'
      working-directory: site
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git checkout  gh-pages
        git add -f dist
        git commit -m "Automated site build"
        git push -f origin gh-pages
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          site:
            - 'site/**'
          database:
            - 'database/**'
    - name: Checkout
      if: steps.filter.outputs.database == 'true' || steps.filter.outputs.site == 'true'
      uses: actions/checkout@v3
      with:
       ref: gh-pages
    - name: Upload artefacts
      if: steps.filter.outputs.database == 'true' || steps.filter.outputs.site == 'true'
      uses: actions/upload-pages-artifact@v1
      with:
        path: site/dist
    - name: Deploy to GitHub Pages
      if: steps.filter.outputs.database == 'true' || steps.filter.outputs.site == 'true'
      id: deployment
      uses: actions/deploy-pages@v2
